In [1]:
import cv2
import numpy as np
import os

In [10]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))
cv2.imshow("Image", img_resize)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
img_resize.shape

(720, 1280, 3)

In [4]:
img_resize[:,:,0]  # Blue Image Channel

array([[ 44,  44,  43, ..., 128, 129, 130],
       [ 43,  42,  42, ..., 129, 130, 131],
       [ 41,  41,  40, ..., 130, 131, 132],
       ...,
       [146, 145, 142, ...,  82, 103, 113],
       [133, 133, 132, ...,  92, 107, 115],
       [125, 125, 125, ...,  98, 111, 117]], dtype=uint8)

In [5]:
img_resize[:,:,1] # Green Image Channel

array([[126, 126, 125, ..., 173, 174, 175],
       [125, 124, 124, ..., 174, 175, 176],
       [123, 123, 122, ..., 175, 176, 177],
       ...,
       [175, 175, 174, ..., 132, 150, 159],
       [174, 174, 173, ..., 136, 150, 157],
       [174, 173, 172, ..., 139, 150, 156]], dtype=uint8)

In [6]:
img_resize[:,:,2] # Red Image Channel

array([[ 91,  91,  90, ..., 154, 155, 156],
       [ 90,  90,  89, ..., 155, 156, 157],
       [ 88,  88,  87, ..., 156, 157, 158],
       ...,
       [142, 141, 140, ...,  94, 113, 123],
       [138, 138, 136, ...,  99, 118, 127],
       [136, 135, 134, ..., 102, 121, 130]], dtype=uint8)

In [11]:
# Convert Image to Gray
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))

# Gray color Conversion

img_gray = cv2.cvtColor(img_resize, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray Image", img_gray)

cv2.waitKey()

cv2.destroyAllWindows()


In [12]:
# Convert Image to HLS
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))

# Gray color Conversion

img_gray = cv2.cvtColor(img_resize, cv2.COLOR_BGR2HLS_FULL)

cv2.imshow("HLS Image", img_gray)

cv2.waitKey()

cv2.destroyAllWindows()


In [15]:
# Convert Image to HSV
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))

# Gray color Conversion

img_gray = cv2.cvtColor(img_resize, cv2.COLOR_BGR2HSV)

cv2.imshow("HSV Image", img_gray)

cv2.waitKey()

cv2.destroyAllWindows()


In [16]:
# Convert Image to YCrCb
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))

# Gray color Conversion

img_gray = cv2.cvtColor(img_resize, cv2.COLOR_BGR2YCrCb)

cv2.imshow("YCrCb Image", img_gray)

cv2.waitKey()

cv2.destroyAllWindows()


In [19]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img_resize = cv2.resize(img,(1280, 720))

# Gray color Conversion

img_gray = cv2.cvtColor(img_resize, cv2.COLOR_BGR2RGBA)

cv2.imshow("YCrCb Image", img_gray)

cv2.waitKey()

cv2.destroyAllWindows()
