 # Splitting images in OpenCv
In OpenCV, the splitting of images refers to the process of separating the color channels of a multi-channel image into individual single-channel images. A typical color image is composed of three color channels: red, green, and blue (RGB). Splitting an image into its individual channels can be useful for various image processing tasks, such as performing operations on individual color components or analyzing color information.



In [3]:
import cv2
import numpy as np

In [10]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat15.jpg"""
img = cv2.imread(img_path)
img = cv2.resize(img,(1280,720))

img.shape




(720, 1280, 3)

In [7]:
img[:,:,0]  # Blue Image Channel

array([[ 44,  44,  43, ..., 128, 129, 130],
       [ 43,  42,  42, ..., 129, 130, 131],
       [ 41,  41,  40, ..., 130, 131, 132],
       ...,
       [146, 145, 142, ...,  82, 103, 113],
       [133, 133, 132, ...,  92, 107, 115],
       [125, 125, 125, ...,  98, 111, 117]], dtype=uint8)

In [8]:
img[:,:,1]  # Green Image Channel

array([[126, 126, 125, ..., 173, 174, 175],
       [125, 124, 124, ..., 174, 175, 176],
       [123, 123, 122, ..., 175, 176, 177],
       ...,
       [175, 175, 174, ..., 132, 150, 159],
       [174, 174, 173, ..., 136, 150, 157],
       [174, 173, 172, ..., 139, 150, 156]], dtype=uint8)

In [9]:
img[:,:,2]  #  Red Image Channel

array([[ 91,  91,  90, ..., 154, 155, 156],
       [ 90,  90,  89, ..., 155, 156, 157],
       [ 88,  88,  87, ..., 156, 157, 158],
       ...,
       [142, 141, 140, ...,  94, 113, 123],
       [138, 138, 136, ...,  99, 118, 127],
       [136, 135, 134, ..., 102, 121, 130]], dtype=uint8)

In [11]:
b, g, r = cv2.split(img)  

In [14]:
import time

# This line captures the current time as the starting point for measuring the execution time of the following code.
start_time = time.time()

for i in range(100):
    r, g, b = cv2.split(img)
    
# This line captures the current time after the loop has finished.
end_time = time.time()

print("Total time taken to split 100 Images: ", end_time - start_time)

Total time taken to split 100 Images:  0.3133993148803711


# Merging of Images in OpenCV

In OpenCV, merging images refers to the process of combining multiple single-channel or multi-channel images into a single multi-channel image. This is often used when you want to overlay images, blend them, or recombine separated color channels back into a full-color image. The primary function used for merging images is cv2.merge().

For example, if you have split an image into its red, green, and blue color channels using cv2.split(), you can merge them back together using cv2.merge() to reconstruct the original full-color image. Similarly, if you have multiple images and you want to overlay or blend them, you can merge them into a single image using appropriate techniques.

In [15]:
import cv2
import numpy as np

In [17]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat13.jpg"""

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

b, g, r = cv2.split(img)

img_merge = cv2.merge([b,g,r])

cv2.imshow("Cat13 Blue Image", b)
cv2.imshow("Cat13 Green Image", g)
cv2.imshow("Cat13 Red Image", r)

cv2.imshow("Merge Cat13 Image", img_merge)

cv2.waitKey(0)
cv2.destroyAllWindows()