# Convert Color Or Gray Image Into Blue Green Red Image Using OpenCV Python

In [1]:
import cv2
import numpy as np

In [4]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat13.jpg"""
img = cv2.imread(img_path)
#img = cv2.resize(img, (1280, 720))

cv2.imshow("Color image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
 img.shape

(640, 612, 3)

In [6]:
# Blue Image

b, g, r = cv2.split(img)

zeros_ch = np.zeros(img.shape[0:2], dtype = "uint8")

blue_img = cv2.merge([b,zeros_ch, zeros_ch])

cv2.imshow("Blue Image", blue_img)

cv2.waitKey(0)

cv2.destroyAllWindows()



# Seperation of different color channels
Explanation of Changes:

empty_channel = np.zeros_like(b): Here, we create an empty channel array filled with zeros. This array has the same dimensions as the blue channel. It represents an empty blue or red channel.

green_channel_only = cv2.merge((empty_channel, g, empty_channel)): This line merges the original green channel (g) with two empty channels for blue and red. The result is an image where only the green channel has non-zero values, effectively extracting the green channel.

The rest of the code remains the same as before. This modified code will display an image where only the green channel values are retained, while the blue and red channels are filled with zeros.



In [14]:
# Seperate Chennel i.e. green can be extracted in the follwing way as well

import cv2
import numpy as np

# Load an image
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat13.jpg"""
img = cv2.imread(img_path)

# Split the image into its color channels
b, g, r = cv2.split(img)

# Create an empty blue and red channel arrays
empty_channel = np.zeros_like(b)

# Merge the blue channel with empty green and red channels to visualize
green_channel_only = cv2.merge((empty_channel,g, empty_channel))

# Display the blue channel extracted image
cv2.imshow("Green Channel", green_channel_only)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Array demostration of Seperating Blue Channel Only

Original Image:
[[[ 90 120 255]
  [ 40  70 180]
  [150 200 100]]

 [[210 240  60]
  [130 160 220]
  [ 80 110 190]]

 [[170 140 210]
  [250 220 170]
  [230 200 150]]]

b, g, r = cv2.split(img): This line splits the image into its blue (b), green (g), and red (r) color channels.

empty_channel = np.zeros_like(g): Here, we create an empty channel array filled with zeros. This array has the same dimensions as the green channel. It represents an empty green or red channel.

blue_channel_only = cv2.merge((b, empty_channel, empty_channel)): This line merges the original blue channel (b) with two empty channels for green and red. The result is an image where only the blue channel has non-zero values, effectively extracting the blue channel.


Extracted BlUE image:

Blue Channel Extracted Image:
[[[ 90   0   0]
  [ 40   0   0]
  [150   0   0]]

 [[210   0   0]
  [130   0   0]
  [ 80   0   0]]

 [[170   0   0]
  [250   0   0]
  [230   0   0]]]


In [13]:
import cv2
import numpy as np

# Load an image
img_path = r"""F:\OpenCV  Tutorials\Image_data\cat13.jpg"""
img = cv2.imread(img_path)

# Split the image into its color channels
b, g, r = cv2.split(img)

# Create an empty green and red channel arrays
empty_channel = np.zeros_like(g)

# Merge the blue channel with empty green and red channels to visualize
blue_channel_only = cv2.merge((b, empty_channel, empty_channel))

# Display the blue channel extracted image
cv2.imshow("Blue Channel", blue_channel_only)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Alternative Method - Seperation of Blue/Green/Red Channel



In [19]:
b, g, r = cv2.split(img)

# img.shape was (640, 612, 3)
zeros_ch = np.zeros(img.shape[0:2], dtype = "uint8") # it creates an array or zeros of (640, 612) due to img.shape[0:2]  


blue_img = cv2.merge([b,zeros_ch, zeros_ch]) # b and other channel array of zeros acc to b,g,r gives blue channel and vice versa 
green_img = cv2.merge([zeros_ch, g, zeros_ch])
red_img = cv2.merge([zeros_ch,zeros_ch, r])

cv2.imshow("Original Image", img)
cv2.imshow("Blue Image", blue_img)
cv2.imshow("Green Image", green_img)
cv2.imshow("Red Image", red_img)

cv2.waitKey(0) 
cv2.destroyAllWindows()