In [18]:
import cv2
import numpy as np

In [24]:
img_path = r"""F:\OpenCV  Tutorials\Image_data\road5.jpg"""

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

cv2.imshow("Road", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# Convert to Gray_Scale

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Road",gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [26]:
gray_image  # Image range = 0 - 255 # Black = 0 and White = 255

array([[231, 226, 227, ..., 189, 183, 186],
       [223, 231, 223, ..., 181, 186, 186],
       [222, 234, 223, ..., 189, 192, 187],
       ...,
       [ 34,  43,  53, ...,  42,  46,  48],
       [ 35,  43,  55, ...,  43,  42,  37],
       [ 32,  34,  35, ...,  40,  34,  40]], dtype=uint8)

In [31]:
# Copying the image

gray_image_copy = np.copy(gray_image)

# if a pixel value of in the image is less than 180 allocate it to zero so that only white pixel left behind

gray_image_copy[gray_image_copy[:,:] < 180] = 0

cv2.imshow("White Pixel Road",gray_image_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [33]:
gray_image_copy[:,:] < 180

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [36]:
gray_image_copy[:,300]

array([227, 230, 234, 227, 231, 224, 230, 223, 220, 235, 229, 221, 238,
       230, 225, 219, 221, 229, 224, 231, 233, 222, 227, 227, 234, 226,
       228, 216, 227, 226, 225, 220, 219, 227, 220, 228, 224, 224, 226,
       231, 226, 231, 232, 234, 229, 222, 231, 228, 231, 230, 228, 225,
       230, 228, 225, 227, 220, 228, 219, 220, 208, 218, 216, 208, 215,
       214, 212, 216, 217, 216, 213, 216, 219, 222, 214, 211, 214, 213,
       221, 215, 219, 217, 215, 215, 211, 217, 216, 205, 209, 213, 217,
       214, 212, 215, 213, 210, 224, 221, 227, 226, 226, 222, 219, 221,
       181, 219, 216, 223, 216, 213, 218, 215, 210, 215, 221, 218, 212,
       215, 212, 212, 221, 217, 220, 215, 223, 184, 228, 218, 221, 209,
       224, 213, 216, 214, 212, 213, 218, 221, 217, 214, 217, 206, 215,
       210, 213, 212, 222, 213, 214, 249, 225, 217, 213, 212, 230, 243,
       209, 214, 208, 216, 209, 219, 215, 214, 210, 217, 219, 211, 212,
       219, 211, 215, 219, 212, 217, 210, 214, 210, 208, 215, 21

In [37]:
# Road Margin Detection using Color image

img_copy = np.copy(img)



In [38]:
img_copy.shape

(720, 1280, 3)

In [41]:
img_copy[(img_copy[:,:,0] < 200) | (img_copy[:,:,1] < 200) | (img_copy[:,:,2] < 200)] = 0
img_copy

cv2.imshow("Color Image Edge",img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
