In [1]:
# Syntax: cv2.imshow(Window_name, ndarray)
# This fuction helps in showing numpy arrays in the form of image

In [2]:
import cv2
import numpy as np

In [3]:
matrix = np.zeros((200,200)) # Array of zeros 200 x 200, zeros means black pixel value - displays a black image
print(matrix)

cv2.imshow("Black image", matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
path = r"""F:\OpenCV  Tutorials\Image_data\cat12.jpg"""

img = cv2.imread(path, -1)

cv2.imshow("Cat12 ", img)    # Shows picture according to our screen resolution
cv2.imshow("Cat12 1 ", img)
cv2.imshow("Cat12 2 ", img)
cv2.waitKey(0)
cv2.destroyAllWindows()